### ISSUE TITLE
Generating the lb.config.ts values from loopback config.json file

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#101]
At [First Steps](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/4.-First-Steps) it is explained that it is a must to configure the SDK but I noticed that I can also update the lb.config.ts file directly with the same result.

Would it be possible to have this generated from the loopback config.json file directly during the sdk build process?

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag, the lb.config.ts file is relatively new in the sdk builder and I do have been considering  to use the config.json files since more parameters and options are about to come in new releases, so adding all of these parameters in command line will turn annoying so I just added the enhancement label and it is possible that will be implemented soon.

Cheers
Jon!!!
