### ISSUE TITLE
Passport Social Logins

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#102]
I am having difficulties implementing social logins using the sdk.

Tried to generate the sdk (-d ng4web -i disabled) for [loopback-example-passport](https://github.com/strongloop/loopback-example-passport) but am at a loss on how to do the social login.

Let me know if this shouldn't be in the scope of this project and would appreciate pointers into the right direction.

Thanks
Julian

**Comment by jonathan-casarrubias** [comment]
Hello @dmastag, thanks for reaching out... The Passport was not in the original scope because there was no good way to share components, now that it exist the NgModule it is possible to provide a component that help developers to integrate it.

But, as I said is just to help developers because there are other configurations aside the SDK builder to achieve this and currently can be implemented without such help.

I may add documentation for now to help others achieve this, but I will try to roughly explain here to you and later I can polish and add it to the WIKI.

Instructions
===========


1.- The loopback-component-passport will create the endpoints that you configure like /auth/facebook for instance.

2.- So literally in your ng2 app you just need a regular link that points to that endpoint.

3.- Then the callback path should point to a remote method you create in the backend, in there you will have access the accessToken and newly created userId.

4.- Then you can redirect the user to a front end path you need to define in your Application Routes, something like:

/passport/:id/:userId

5.- In that point you will have access to an AccessToken Instance in Angular2, but you still need to locally persist it with localStorage.

For that you can use the LoopBackAuth service provided by the SDK Builder


````js
import { AccessToken } from './shared/sdk/models';
import { LoopBackAuth } from './shared/sdk/services';
import { Router, ActivatedRoute } from '@angular/router';

@component(...)
class PassportComponent {

  constructor(
    private auth: LoopBackAuth,
    private route: ActivatedRoute,
    private router: Router
  ) {
    this._route.params.subscribe((token: AccessToken) => {
      if (token.id && token.userId) {
        this.auth.setUser(token.id, token.userId, {});
        this.auth.setRememberMe(true);
        this.auth.save();
        this.router.navigate(['/account']);
      }
    });
  }
}
````

This definitely works since I got this working in one of my projects.

Again, now that there is the NgModule concept I may create a PassportComponent that comes built in with the SDK, so I will add this issue a Nice to Have and Enhancement tags

Cheers!!
Jon

**Comment by dmastag** [comment]
Appreciate that you took the time to create the instructions mate :smiley: 
And will keep an eye on the enhancement.

**Comment by LiorArbel** [comment]
hey @jonathan-casarrubias , for some reason I added the route but it doesn't recognize `req.accessToken` at all. 
I did everything you wrote in your answer.

**Comment by jonathan-casarrubias** [comment]
Hey @LiorArbel thanks for reaching out..

Hey so, make sure you follow this instructions first: https://loopback.io/doc/en/lb2/Third-party-login-using-Passport.html

More specifically, I believe you are missing the session part within the server.js

```js
// Enable http session
app.use(loopback.session({ secret: 'keyboard cat' }));
```

This way LoopBack is able to get the session token etc.

I hope this helps you fix your issue.

Cheers
Jon

**Comment by LiorArbel** [comment]
@jonathan-casarrubias I already had that line that's no the solution...
But,  I managed to fix it now by adding the cookie parser and reading the `req.cookies.userId` and `req.cookies.access_token`. 

I think the documentation is outdated.

Now I'm stuck at 
```
this.route.params.subscribe((token: AccessToken) => {
      if (token.id && token.userId) {
        this.auth.setUser(token.id, token.userId, {});
        this.auth.setRememberMe(true);
        this.auth.save();
        this.router.navigate(['/account']);
      }
    });
```
Since `this.auth.setUser` needs to receive an SDKToken per the implementation of your auth service.
`token.id, token.userId, {}` is not an SDKToken.

**Comment by jonathan-casarrubias** [comment]
Right, but the SDKToken extends from AccessToken, I have not tested this in a while but technically the following should work

````js
this.route.params.subscribe((token: SDKToken) => {
      if (token.id && token.userId) {
        this.auth.setUser(token.id, token.userId, {});
        this.auth.setRememberMe(true);
        this.auth.save();
        this.router.navigate(['/account']);
      }
    });
````

**Comment by LiorArbel** [comment]
@jonathan-casarrubias The problem is still the line
```
this.auth.setUser(token.id, token.userId, {});
```
It throws an "Supplied parameters do not match any signature of call target" ts exception

**Comment by jonathan-casarrubias** [comment]
Oh I see, I just verified the code as it is right now, and you should pass the entire dependency

````js
this.route.params.subscribe((token: SDKToken) => {
      if (token.id && token.userId) {
        this.auth.setUser(token);
        this.auth.setRememberMe(true);
        this.auth.save();
        this.router.navigate(['/account']);
      }
    });
```` 

this is the setUser declaration

````js
  public setUser(token: SDKToken) {
    this.token = Object.assign(this.token, token);
  }
````

**Comment by LiorArbel** [comment]
@jonathan-casarrubias Thank you, that worked. It would be nice if you could update the documentation - both about the SDKToken and the cookies thing

**Comment by jonathan-casarrubias** [comment]
Hi @LiorArbel I did update the documentation to  SDK Token, I will add a note for cookieParser

Im glad you make it work

Cheers
Jon

**Comment by KingsDevelopment** [comment]
@jonathan-casarrubias my problem with your latest example is that the cookies are not being set.
I console logged it in the cookiebrowser class, and with the normal login it goes perfectly fine.

But when I am using the redirect from loopback, the cookies are not being set. (Tried on seperate domains etc)
