### ISSUE TITLE
Ability to skip certain attributes

### ISSUE THREAD

**Issue by mevinDhun** [mean-expert-official/loopback-sdk-builder#116]
Hi,

Is there any way to tell the generator to skip certain attributes on specific models? Also, can we specify which models to skip completely? I remember before you set up the wiki, there was some documentation on marking models as private but i cannot find it anymore.

**Comment by jonathan-casarrubias** [comment]
Hi @mevinDhun.

Currently you can avoid creating the complete model if you set the Model as private in server/model-config.json.

Also you can blacklist some methods by adding the following configuration in your model.json

````json
{
  "sdk": {
    "blacklist": {
      "methodName": true
    }
  }
}
````
At this moment there is no way to disable properties and I'm not sure this would be implemented in the short term.

Hope this information helps.

Cheers!
Jon

**Comment by mevinDhun** [comment]
Thanks, i managed to make it work by marking it as private. I noticed when i ran the command to generate the sdk, it started my loopback app server. Is that normal?

![screen shot 2016-09-12 at 8 37 03 pm](https://cloud.githubusercontent.com/assets/17478561/18444121/0429e760-7929-11e6-80f6-c53809bbc1a5.png)

**Comment by jonathan-casarrubias** [comment]
Hi @mevinDhun yes that is a normal behaviour, the Builder needs a running version of the application in order to be able to explore how LoopBack is structuring the API.

In other words, the sdk is not generated from the configuration files, but from an actual app context.

Btw. I'm glad you were able to disable the model your self.

Cheers!!
Jon

**Comment by mevinDhun** [comment]
When i mark the models as private, the generator skips them as expected but still includes them if they are being used in relations. For example, i have a User which has a relation logins with LoginAttempt. When i mark LoginAttempt as private, the relation logins is still generated and hence will not compile. Is this an intended behaviour?

**Comment by jonathan-casarrubias** [comment]
Hi @mevinDhun thanks for reaching me out.

Well not really, the expected behaviour is that private models won't be included in the relations.
For instance

ModelA hasMany ModelB

but lets say that ModelB is private, then the expected behaviour is that ModelB should not be represented in any place of the SDK, no model included, no service included but the relations is a complex topic.

So...

ModelA.modelBrelation property should be treated as an Array of any

````js
class ModelA {
  modelBrelation: Array<any> // insteado of  Array<ModelB>
}
````

Not sure why is not working for you, in the Unit Tests I have that use case tested:

Private Model: https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/loopback/model-config.json#L42

Relation Room hasMany Message: https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/common/models/room.json#L20

Treated relationship: https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/src/app/shared/sdk/models/Room.ts#L11

So, it is possible that you may have a specific use case not being treated, this has been a though feature and it may be a missing part to be fixed, but I will need you to specify the relationships between these models.

Cheers!
Jon

**Comment by mevinDhun** [comment]
Below are some details:

EboardUser has relation loginAttempts:
````javascript
"loginAttempts": {
      "type": "hasMany",
      "model": "LoginAttempt",
      "foreignKey": "idUser"
    }
````
LoginAttempt is marked as private:
````javascript
 "sdk": {
        "private": true
    }
````
The generated EboardUser.ts has login attempts which should not be there:
````javascript
loginAttempts: Array<LoginAttempt>;
````
Note: i am using sdk builder v2.0.9

**Comment by jonathan-casarrubias** [comment]
I see, that is strange because I'm not sure why you get a difference by using that property, which is not implemented.

There is nothing inside the reads that property, so It is a strange case.

Anyway, the right place to set your models to private is in the following file

````sh
$ vim path/to/loopback/server/model-config.json
````  

example:

````json
{
  "Message": {
    "dataSource": "db",
    "public": false
  }
}
````

In other words, I'm using the built-in functionality in order to not exposing APIs.

Cheers
Jon
