### ISSUE TITLE
Question: HEAD request type

### ISSUE THREAD

**Issue by ostapch** [mean-expert-official/loopback-sdk-builder#126]
Hi @jonathan-casarrubias . Can you help me, please.

I have such error and haven't any idea to resolve this

![selection_002](https://cloud.githubusercontent.com/assets/12660249/18944387/fb91ff22-862d-11e6-8b3e-be7f3581a023.png)

**Comment by jonathan-casarrubias** [comment]
Hi @ostapch this endpoint is usually created to verify the existence in terms of relations between clients and companies.

So you probably are calling Client.existCompanies

If you get a 404 it means the relation is not yet created then you will be able to link the relation, this is an expected behavour from LoopBack, when checking for a relation and this does not exist will throw a 404 then you are able to link the relations.

Cheers
Jon

**Comment by dmober** [comment]
Hi! How can we process this error for save our console clear?

**Comment by jonathan-casarrubias** [comment]
@dmober well, that is the natural LoopBack behaviour (404 when relation does not exist, 200 when relation exist), so... You would need to change that built in behaviour either by creating your own remote method that returns an object describing whether if the relation exist or not.

But I also think as an alternative to use an operation hook that change the results from the built in endpoint, so instead of returning the result using HTTP Codes you may be able to return an object and always throw a 200 status code in order to maintain the console clean.

Either the case, the SDK Builder is not responsible for the 404 return code, but whatever approach you choose to clean your console, it is able to use the remote method you create or if you decide to hook the built in method, then it would be transparent for the builder.

Hope this information is helpful for you guys.

Cheers
Jon
