### ISSUE TITLE
Duplicate identifier if relation name is same as foreign key

### ISSUE THREAD

**Issue by bostondv** [mean-expert-official/loopback-sdk-builder#139]
Generating SDK with a model that has a relation with same name and foreign key will create a client interface with duplicate identifiers.

example server model.json:

```
relations: [
    "creator": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "creator"
    }
]
```

will produce this in client model.ts

```
export interface ModelInterface {
  creator?: number;
  creator?: User;
}
```

I'm not sure if having a relation name with same foreignKey is bad practice, but it might be something to check for and handle in the SDK generation?

**Comment by jonathan-casarrubias** [comment]
@bostondv thanks for reaching me out.

Well, this time it is actually a bad practice because you will get multiple errors along the different layers, not only the SDK one.. 

You MUST not set the foreignKey with the same name as the relationship because one handles the ID reference and the other handles the relationship, therefore it should be different.

The natural LoopBack behavior is that automatically adds the foreign key by taking the relationship name plus "Id" postfix.

In your case the correct foreign key should be "creatorId" if you simply keep it unset, if you really needed to change the foreignKey, then you would need to add a subject plus Id postfix.

Like: ownerId, or something like that.

Hope this information is helpful for you.

Cheers!!
jon

**Comment by bostondv** [comment]
Thanks for the clarification! I had a feeling what i was doing was a bad
practice :)

Unsetting or changing the foreignKey to something different worked like a
charm.
