### ISSUE TITLE
Problem using "and" operator in query parameter

### ISSUE THREAD

**Issue by techla** [mean-expert-official/loopback-sdk-builder#148]
Hi, I'm actually using your SDK builder and tried to compose a query.
Here is the query wich is not working : 

myModel.find({"where":{"and":[{"or":[{"company_name":{"regexp":"/r/i"}},{"email":{"regexp":"/r/i"}},{"first_name":{"regexp":"/r/i"}},{"last_name":{"regexp":"/r/i"}}]}]}})

I think the problem is coming from the "and" operator because without it, it seems to work.

**Comment by jonathan-casarrubias** [comment]
hi @techla thanks for reporting..

I will verify... just to confirm which version of the builder are you using?

Cheers
Jon

**Comment by techla** [comment]
I'm on the 2.0.8 version

**Comment by jonathan-casarrubias** [comment]
I think your issue is related with this: https://github.com/mean-expert-official/loopback-sdk-builder/issues/132

That is already fixed but under the 2.1.0-beta.6 version.

You may try this one, but there are some changes... now the Builder defaults the IO Functionality, if you are not using it... just disable it.

Please confirm if that fixes your issue, I'm pretty sure it should fix it.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hi @techla did you issue persisted? were you able to fix it by upgrading the SDK Version?

Regards,
Jon

**Comment by jonathan-casarrubias** [comment]
Anyhow, the way filters are passed is going to change again in favor of this https://github.com/mean-expert-official/loopback-sdk-builder/issues/151

Filters won't be sent over query params but headers. it should also work best

**Comment by jonathan-casarrubias** [comment]
Fixed
