### ISSUE TITLE
Connect to multi loopback microservice

### ISSUE THREAD

**Issue by hkashlan** [mean-expert-official/loopback-sdk-builder#150]
how to handle generate sdk for **multi  loopback microservices** in **one client for me ionic**, and to say this angular service for this microservice :worried::worried:

it will be good if we can **handle multi loopback services in one client** :blush::blush:

I think the questions will be:
1. how to define (BASE_URL,API_VERSION, LoopBackConfig) for every microservice.
2. conflict files between 2 microservices

My Case:
I have a micro services environment
1-microservice 1 based on loopback.
2-microservice 2 based on loopback.

and I have generate 2 sdk folder (sdkMS1, sdkMS2) inside shared

and I have index.ts inside the shared:
export \* from './sdkMS1';
export \* from './sdkMS2';

the error is 
**[ts] Module './sdkMS1' has already exported a member named 'ErrorHandler'. Consider explicitly re-exporting to resolve the ambiguity.
[ts] Module './sdkMS1' has already exported a member named 'API_PROVIDERS'. Consider explicitly re-exporting to resolve the ambiguity.
[ts] Module './sdkMS1' has already exported a member named 'AccessTokenInterface'. Consider explicitly re-exporting to resolve the ambiguity.
[ts] Module './sdkMS1' has already exported a member named 'BaseLoopBackApi'. Consider explicitly re-exporting to resolve the ambiguity.
[ts] Module './sdkMS1' has already exported a member named 'Container'. Consider explicitly re-exporting to resolve the ambiguity.**

**Comment by jonathan-casarrubias** [comment]
hi @hkashlan thanks for reaching out.

Hey so, if you have different loopback instances, with different structure by using microservices architecture, for now the sdk won't work.

It is designed to work with 1 schema, eventhough you can point the different services to different domains or api versions.

But if I understand well, your 2 loopback instances are different, with different schema so... a refactor would be needed in order to support this..

**Comment by hkashlan** [comment]
@jonathan-casarrubias  thank you for your reply
yes what I have 2 loopback instances , with different schema 

I will look at your code and check if I can help in refactoring

if this is ok for you :blush::blush:

**Comment by jonathan-casarrubias** [comment]
Hey @hkashlan I really appreciate your offer to work on this.

Currently, the SDK builder support a good amount of use cases, and most of the times that I receive pull requests, these only consider the use case of the person creating the pull request, but there are many use cases that I need to make sure are not broken. 

Usually is fine by making sure the current tests are not broken and adding new for the new use case. 

But this type of refactor would be so deep that everything would change, even the final implementation would need to be changed, therefore the current tests and documentation, which basically means that we may break not less than 1k applications using this software.

In order to achieve this, we would need to 

1.- Decouple the core from custom client models, services and interfaces. so the cli tool would usually create 2 or n modules instead of 1 (SDKCoreModule and {Prefix}SDKModule, N).

2.- Update all of the tests and adding one.

3.- Revisit the Wiki Documentation and Mean Expert Blog articles.

4.- Refactor current applications using the SDK Builder (My own, customers and from the community)

As you can see, this change would be so big that I would even need to increase the version to number 3 .

Unfortunately there are a number of features still pending that are priority, like the Angular Universal integration and Infinite Child Reference for FireLoop and WebRTC Implementation that I would not be able to handle a refactor like this for now.

So, this entire work took a lot of months and the stable version has been around just 1 month that also for this reason I can not manage a refactor like this for now.

The good part of this is that the SDK has been constantly growing that decoupling some of the components seems to be imminent in the future. Originally this was just a port of the sdk angular to Angular 2, but right now has taken a totally different direction so I can promise that once the other priority features I will (and you may help if you want) decouple everything into multiple modules, making possible what you are trying to achieve.

I'm sorry for not being able to handle this request at this moment.

Regards
Jon
