### ISSUE TITLE
FireLoop ACL Integration

### ISSUE THREAD

**Issue by nikiman** [mean-expert-official/loopback-sdk-builder#164]
Actually if I try to upsert an object in Authentication mode, the console shows me an error: 

`PUT http://0.0.0.0:3000/api/Accounts 401 Unauthorized 6ms
NetworkError: 401 Unauthorized - http://0.0.0.0:3000/api/Accounts`

**Comment by jonathan-casarrubias** [comment]
Hey @nikiman thanks for contributing with this issue.

So, yesterday I took the time to verify and actually found that I was actually able to persist through FireLoop without ACL Issues. which is actually wrong I should receive an unauthorized method.. I need to keep reviewing why.

So, after reviewing again your error log, I see it says PUT.. which is a revelation because when using FireLoop does not use HTTP Methods like POST or PUT.

Are you using for instance

AccountApi.upsert()? this is the one that actually uses PUT method.

I have tested the following

````js
import { Component, OnInit } from '@angular/core';
import { Account, FireLoopRef } from '../shared/sdk/models';
import { AccountApi, LoggerService, RealTime } from '../shared/sdk/services';

@Component({
  selector: 'app-room',
  templateUrl: 'room.component.html'
})

export class RoomComponent implements OnInit {

  private logged: Account;
  private accountRef: FireLoopRef<Account>;

  constructor(
    private accountApi: AccountApi,
    private logger: LoggerService,
    private realTime: RealTime
  ) {
    this.logged = this.accountApi.getCachedCurrent();
    this.accountRef = this.realTime.FireLoop.ref<Account>(Account);
  }

  update(): void {
    this.accountRef.upsert(this.logged).subscribe(res => console.log(res));
  }
}
````

see that Im using the accountRef.upsert instead of accountApi.upsert.

Anyhow, now I need to verify the opposite, why is not looking for ACLs and persisting any the way.

Cheers
Jon

**Comment by nikiman** [comment]
@jonathan-casarrubias you're absolutely right! 
I checked the code again and the problem was just that I was using the accountApi.upsert instead of accountRef.upsert.

Now it works without a hitch!
Thank you! ;)

**Comment by jonathan-casarrubias** [comment]
Hey @nikiman,

Now FireLoop implements the ACLs, so you either can use it with open or closed rules, of course when no access is granted then the event will fail.

Thanks for reporting this important issue

Cheers
Jon

**Comment by tabvn** [comment]
Jonathan, if you are looking for this featured i have done this https://github.com/tabvn/loopbackCMS
see Video how it works: https://www.youtube.com/watch?v=z38B_iA4fJI
