### ISSUE TITLE
Web app and nativescript combined - how to handle the different 

### ISSUE THREAD

**Issue by tfiwm** [mean-expert-official/loopback-sdk-builder#171]
#### What type of issue are you creating?
- [x] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)

Write other if any:

#### Please add a description for your issue:
I am using [nativescript-ng2-magic](https://github.com/NathanWalker/nativescript-ng2-magic).
With the builder you can export for both platforms but the problem what i have is, that i have to import the ngModule. Do you have already experience to use OpaqueToken for the different services -> as i see it is only the storage which is different right?

I know how to use the OpaqueToken but no idea how to handle it with the ngModule from the sdk. If you have already experience with it i am happy to here something otherwise i will try to find a way to handle this and not to destroy the export function for me

**Comment by jonathan-casarrubias** [comment]
Hi @tfiwm! Thanks for reaching out, 

Hey so... There are a couple if things that are different, 1 is the local storage and second the socket.io adapter is different library depending the environment.

If you don't set real-time functionalities in your sdk, then the only difference would be the local storage.

Currently how it works is that LoopBack already provides with an AccessToken model, which is handled through the complete system. 

The SDK Builder basically replicates all of your Models and Remote Methods for your Angular 2 client, including the AccessToken from LoopBack with its schema.

Which this is neither a string, is a Model I haven't seen the value in wrapping it inside a Service, mostly because I want to keep the Models uncoupled from Angular 2.

Anyway, you may be able to extend the AccessToken model and create an OpaqueToken Service, I feel confident that should work if you need for some reason -requirement- to use OpaqueToken services.

Please see the wiki documentation for [Extending Models](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/6.-Extending-Client-Models)

I hope you find this information useful.

Cheers!
Jon
