### ISSUE TITLE
Remote Method missing

### ISSUE THREAD

**Issue by rossimo** [mean-expert-official/loopback-sdk-builder#172]
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.0.10 (Stable)

#### Please add a description for your issue:
It seems none of my remote methods are showing up in the client SDK. Here is example source.

sample.json:
```
{
  "name": "Sample",
  "plural": "Samples",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "age": {
      "type": "number",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

sample.ts:
```
import {PersistedModel} from 'loopback'

interface Sample extends PersistedModel {
    agePlusOne(id: string): Promise<number>
}

module.exports = function (sample: Sample) {
    sample.remoteMethod('agePlusOne', {
        accepts: {arg: 'id', type: 'string', required: true},
        http: {path: '/:id/agePlusOne', verb: 'get'},
        returns: {arg: 'newAge', type: 'number'}
    });

    sample.agePlusOne = async(id: string) => {
        let data = await sample.findById(id);
        return data.age + 1;
    }
};
```

**Comment by rossimo** [comment]
Loopback TS definition here: https://gist.github.com/rossimo/3ebdcea865765e5511867235a92678fd

**Comment by jonathan-casarrubias** [comment]
Hi @rossimo!!! Thanks for reaching out,

Hey so... That is strange, remote methods were implemented a long time ago, actually there are several unit test for that.

Backend:
https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/common/models/room.js

Frontend:
https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/src/app/room-service.service.spec.ts#L165

The problem is that I don't really see a problem on your configurations.

The only 2 things I can think

1.- You have set the model as private within model-config.json
2.- You are not transpiling your code to regular JS

If your common/models/*.js are not updated the SDK Builder won't be able to see the changes.

The SDK does turn on your API in order to analyze it, so.. since you are using TS, just make sure everything is compiled prior the SDK Build.

Let me know if you find this information useful.

Regards
Jon

**Comment by rossimo** [comment]
The model is public in model-config.json. I'll look at how the Typescript may be affecting things. I typically don't use transpiling on the sever side. There, I use ts-node to pick up the Typescript source automatically.

Does loopback-sdk-builder throw a warning if the *.js source is missing for JSON model definition?

**Comment by jonathan-casarrubias** [comment]
It does not throw a warning.

Actually what happen under the hood is that the SDK Builder loads the server/server file, once loaded it analyzes the loaded app context.

This means that it will construct whatever is loaded in your App.

if the LoopBack server was not able to load something, the SDK Builder would not be able to see it. So, if you simply run `$ node server/server` whatever it loads by doing that, is the same the SDK Builder is seeing.

For me it seems then that the methods are not being loaded because there are no js files to be loaded by the server.js

**Comment by rossimo** [comment]
The method shows up in the loopback API explorer, which confuses me. For reference, here's my server boot:

```
'use strict';

const loopback = require('loopback');
const boot = require('loopback-boot');

var app = loopback();

boot(app, __dirname, function (err) {
    if (err) throw err;

    if (require.main === module) {
        app.listen(() => {
            app.emit('started');

            var baseUrl = app.get('url').replace(/\/$/, '');
            console.log('Web server listening at: %s', baseUrl);

            if (app.get('loopback-component-explorer')) {
                var explorerPath = app.get('loopback-component-explorer').mountPath;
                console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
            }
        });
    }
});

module.exports = app;
```

**Comment by rossimo** [comment]
Ooooh, this works:

```
./node_modules/.bin/ts-node ./node_modules/\@mean-expert/loopback-sdk-builder/bin/lb-sdk server/server.ts ./client/sdk --wipe enabled --io disabled
```

**Comment by jonathan-casarrubias** [comment]
Awesome. On glad you were able to make it work!!

Cheers.
Jon
