### ISSUE TITLE
How to upload files to storage

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#180]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.14
- [ ] 2.0.10 (Stable)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I can't seem to understand how to use file storage containers and upload files. I see in the code that its still using :container to get the container name but its not included in the function variables (hope I am making any sense).

Could you kindle explain (if possible with a quick ng example) how to upload files?

Thanks before
Julian

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag, I'm glad to see you back.

Hey so, this is a good question... This is an issue being pushed forward since the parent module loopback-sdk-angular, there has never been a real implementation for file upload.

Both, the SDK Builder and SDK Angular create all the methods assuming they all are standard http request, but not multipart or something like that.

The rest of the storage methods that are created do work, so historically what has been the approach is to us the StorageService/API plus ng-file-upload or ng2-file-upload.

The steps would be:

1.- Check if the container exists.
2.- If does not exist, then you create the container. else
3.- use ng2-file-upload to upload to the container you just created.
      The url that you point ng2-file-upload  would be something like:  
      *api/storages/:containerName/upload*
4.- Once it is uploaded, you have to  persist a reference of your uploaded file within the related model.

For example, any profile has a profile photo; therefore what you can do is, to create a container using the profile.id, then you will upload photos or covers from that profile into that container.

Once you have uploaded the image into that container, you persist a property "Profile.photo" or "Profile.cover" with the following structure `{ filename: string, path: string}`.

filename is needed because you will need to remove the file at some point and the name is needed for that. You will always know the container, because will be the model id.

path is needed as reference for not spending resources in calculating the route dynamically every time, so you will just do the following within your template <img [src]="profile.photo.path" />

5.- When you want to remove a container, you just use the profile id.
6.- When you want to remove a single file, then you use the profile id as container name, and then the filename in the following form

[DELETE] /api/storages/:container/files/:filename

I hope this helps you on your implementation.

Cheers
Jon

**Comment by dmastag** [comment]
As always @jonathan-casarrubias thanks for taking the time answering my questions.
Let me try to implement this and I'll let you know if I have any questions.

**Comment by jonathan-casarrubias** [comment]
btw @dmastag do you see any value in opening a community forum for all of these questions?

When these are added as issues they get lost between bugs and features, and I think there are many questions and answers that should persist. So I have been thinking in opening a forum but I would like to know if for instance people like you that are around see any value on it.

I appreciate your answer.

Cheers
Jon

**Comment by dmastag** [comment]
Got it working, thanks.
I am not using ng2-file-upload since its on an ionic2 app and the use case is to copy files from the camera to loopback.

Regarding opening a forum. Its a great idea, but it depends on how strong the community is. For now I think opening Issues here is still good, but I am willing to join if you think a Forum is the way to go.

**Comment by Ellipizle** [comment]
Hi,
I have been trying to do file upload(multi files with meta data) for days. juz like @dmastag i was stunt to see the method was not expecting container name , it just dawn on me to check sdk issues maybe someone must have passed through this process before and final stumble upon this issue.
@jonathan-casarrubias I am also down for a forum.

**Comment by jonathan-casarrubias** [comment]
Hey @Ellipizle, exactly this is the community type of problems that I want to avoid by managing questions related topics in a forum.

I will be setting up a forum soon, hopefully we can see some traffic there... I also believe that if there is no much people participating it will be like dead zone, which could be depressing and I would like to avoid that.

But, truth is that at least this repo has around 15k visits a month by 1.5k users.

So I also believe there is good amount of traffic at least in here, so maybe a forum won't be so lonely.

Thoughts?

**Comment by dmastag** [comment]
A deadzone is definetly something to avoid.
I am also somewhat concerned by the confussion at Ionic. They got different repos for different tools a Forum and a Slack channel, and the questions are all over the place. Maybe some rules?

**Comment by jonathan-casarrubias** [comment]
Yup that is starting to happen in here, so many repos, so many modules. I think that at least at the beginning having all issues within the fireloop repo and just 1 forum for community related topics could work.

right now is getting fragmented, and sometimes it gets difficult to me also to attend all of the repos issues.

But I would really like to keep the repos for bugs, features, etc. and leave a forum or something like that for community related topics.

What you guys think is better, slack channel? forum? none lol. but of course, just 1 place would be the ideal, not both.

**Comment by dmastag** [comment]
Slack of course 👍 
But it will be hard for new comers to get any benefit 👎 
Haven't been in forums for a long long time.

So I think the options would be:
* Use Slack, and use the community input to extend the wiki
* Use a Forum

**Comment by kattsushi** [comment]
hi @dmastag Im agree with the slack, it's excellent for what you want! , It would also be great to have a documentation system in the style of https://angular.io/docs/ts/latest/ and migrate the api docs from the wiki with the tutorial get started!

**Comment by eduinredes** [comment]
Hi, this is still unimplemented in the sdk builder?

**Comment by jonathan-casarrubias** [comment]
@eduinredes well no really, but from that moment to now, we already implemented a way to send custom headers, I know there is people using the SDK generated storage upload method and they passes custom headers to make it work, I believe as "form/multipart" so technically now it works if you configure the method, passing your custom headers.

Cheers
Jon

**Comment by emsedano** [comment]
Another solution would be extend the <Storage>Api and override the upload to use multipart form

`export class ExtendedImageApi extends ImageApi {`
where ImageApi is the name if my Storage (`/api/images/:cointainer/`

```Typescript
/**
   * <em>
   * (The remote method definition does not provide any description.)
   * </em>
   * @param {string} container
   * @param {object} data Request data.
   *  - `req` – `{object}` -
   *  - `res` – `{object}` -
   * @returns {object} An empty reference that will be
   *   populated with the actual data once the response is returned
   *   from the server.
   * Data properties:
   *  - `result` – `{object}` -
   */
  public upload(container: any, file: File): Observable<any> {
    let _method: string = "POST";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
      "/images/:container/upload";
    let _routeParams: any = { container: container };
    let result = this.sendFile(_method, _url, _routeParams, file);
    return result;
  }

  public sendFile(method: string, url: string, routeParams: any = {}, file: File
  ): Observable<any> {
    // Transpile route variables to the actual request Values
    Object.keys(routeParams).forEach((key: string) => {
      url = url.replace(new RegExp(":" + key + "(\/|$)", "g"), routeParams[key] + "$1")
    });
    let headers: Headers = new Headers();
    headers.append('Accept', 'application/json');
    // Authenticate request
    this.authenticate(url, headers);
    // Body will be actually the file
    let body = new FormData();
    body.append('file', file);
    // Separate where object from url params and add to search query
    let request: Request = new Request(
      new RequestOptions({
        headers        : headers,
        method         : method,
        url            : `${url}`,
        body           : body,
        withCredentials: LoopBackConfig.getRequestOptionsCredentials()
      })
    );
    return this.http.request(request)
      .map((res: any) => (res.text() != "" ? res.json() : {}))
      .catch((e) => this.errorHandler.handleError(e));
  }
```
