### ISSUE TITLE
add default null values to generated models classes

### ISSUE THREAD

**Issue by jledun** [mean-expert-official/loopback-sdk-builder#199]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-beta.**17**
- [ ] Other

#### Easy to use model descriptions in Angular

I'm currently developing an angular2 app with loopback and I want the models to be displayed with some added parameters.
Parameters are stored in a loopback model too.

The aim of this application is to permit the user to set :
- is the field can be displayed ?
- what's the tag name to display ?
- other application settings

To do that, I need to know the properties of models. But if models class are generated without default values, there's no properties at all in new models object.

So I've modified :
- bin/lb-sdk to add a -v command line option in order to generate the defaults values in class objects or not (disabled or enabled)
- lib/angular2/index.js : add "buildPropertyDefaultValue(type)" function, insert this function in "buildModelProperty(model, isInterface)", only if it's not interface and ctx.defaultValue is 'enabled'

Now, when I create a new model instance in my angular component, all the interface properties appears with a null value and I can parse them in my component.

**Comment by jonathan-casarrubias** [comment]
Hi @jledun thanks for reaching me out.

Hey so, I see your problem is just that I can see problems in the opposite if just hardcode the null value, of course you took an approach to avoid that.

**But I'm thinking in another approach:**

I usually like to delegate to others the things that they already resolved, in other words lets not reinvent the wheel.

LoopBack already implements default values for properties, why don't we define the default values within the model.json configuration file and the SDK Builder takes the default value if any?

This way is consistent across back and front end what is usually my objective.

Thoughts?

**Comment by jledun** [comment]
Hi @jonathan-casarrubias 

I agree with your approach. It appears simpler and really much more consistent.

Then I'll try to look in this way... Just tell me if it's necessary.

Actually, I've spent half of my day trying to find a way to get model interface details in an angular module with typescript, Googled and duckducked a lot but couldn't find a solution for that. So that's why I'm pushing research in loopback-sdk-builder.

Thank you a lot for the job done with that project ! Pretty time saving !

**Comment by jonathan-casarrubias** [comment]
Yeah you would not be able to add properties into the interface because it is a contract already defined, this needs to be fixed from the origin, before contracts (interfaces) and models are done.

If you can take a look and send a pull request about this feature would be much appreciated.

Currently I'm working really hard in the angular 2 universal integration, so it would be faster.

Cheers
Jon

**Comment by jledun** [comment]
Hey @jonathan-casarrubias !

I've created pull request #212 !

Actually, while writing the pull request detail, I had another idea : to generate a class providing model descriptions, based on loopback models, of course. 
The generated class would be an object represented like that :

```json
{
  "model1": {
    "prop1": {
      "type": "String",
      "default": "value"
    },
    "prop2": {
      "type": "String",
      "default": "value"
    }
  },
  "model2": {
    "prop1": {
      "type": "String",
      "default": "value"
    },
    "prop2": {
      "type": "String",
      "default": "value"
    }
  }
}
```

What do you think about it ?

Regards,
Julien
