### ISSUE TITLE
Arguments in path are not ok on remote methods

### ISSUE THREAD

**Issue by rodplata** [mean-expert-official/loopback-sdk-builder#225]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When I run the builder from my loopback project the sdk do not properly take the arguments that are in the path of the remote method

loopback remote method:
```
Employee.remoteMethod(
    'bySerial',
    {
      accepts: {arg: 'serial', type: 'string', required: true},
      http: {path: '/bySerial/:serial/', verb: 'get'},
      returns: {arg: 'EMPLOYEE', type: 'Object'},
      description: 'Get the employee information using the employee UID',
    });
```

And in the Angular service the _:serial_ is taken as part of the path

```
public bySerial(serial: any): Observable<any> {
    let _method: string = "GET";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/employees/bySerial/:serial/";
    let _routeParams: any = {};
    let _postBody: any = {};
    let _urlParams: any = {};
    if (serial) _urlParams.serial = serial;
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
 }
```

it should be something like
```
`/employees/bySerial/${serial}/`;
```

using back tick, change the `:`to `$` and surround the variable with brackets

**Comment by jonathan-casarrubias** [comment]
Hi @rodplata thanks for reaching out.

In order for the SDK Builder to know which type of param you want to set, you also need to define the http.source configuration, please try the following:

````js
Employee.remoteMethod(
    'bySerial',
    {
      accepts: {arg: 'serial', type: 'string', required: true, http: { source: 'path' }},
      http: {path: '/bySerial/:serial/', verb: 'get'},
      returns: {arg: 'EMPLOYEE', type: 'Object'},
      description: 'Get the employee information using the employee UID',
    });
````

This will assign your serial variable to the _routeParams instead of the _urlParams.

To let you know, the route params are parsed in runtime within the this.request method which is extended from the base api service and it is in there where it changes the :serial key for the actual value, so you won't se something like `/employees/bySerial/${serial}/`; within any of your methods.

I hope this helps you clarify your issue.

Cheers
Jon

**Comment by rodplata** [comment]
Great! that Fix my issue, thank you very much paisano!
