### ISSUE TITLE
Issue when generating sdk

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/loopback-sdk-builder#230]
#### What type of issue are you creating?
- [] Bug ?
- [ ] Enhancement
- [X ] Question

#### What version of this module are you using?
- [X] 2.0.10 (Stable)
- [ ] 2.1.0-beta.14
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hello @jonathan-casarrubias 
When I generate the SDK, I am having the following errors : 

[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/Link.ts:11:3 
    Duplicate identifier 'categoryId'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/Link.ts:13:3 
    Duplicate identifier 'categoryId'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/Link.ts:13:3 
    Subsequent variable declarations must have the same type.  Variable 'categoryId' must be of type 'any', but here has type 'Category'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/Link.ts:22:3 
    Duplicate identifier 'categoryId'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/Link.ts:22:3 
    Subsequent variable declarations must have the same type.  Variable 'categoryId' must be of type 'any', but here has type 'Category'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/models/index.ts:6:15 
    Cannot find module '../../../../../.'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/services/core/io.service.ts:3:10 
    Module '"/Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/services/index"' has no exported member 'AccessToken'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/services/core/real.time.ts:5:10 
    Module '"/Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/services/index"' has no exported member 'AccessToken'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/services/custom/index.ts:6:15 
    Cannot find module '../../../../../../.'.
[default] /Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/sockets/socket.connections.ts:12:10 
    Module '"/Users/IOSoftwareSAS/WebstormProjects/distinguo/angular2client/src/app/shared/sdk/sockets/index"' has no exported member 'AccessToken'.
[default] Checking finished with 10 errors

I think this is coming from "relations". Does the lb-sdk tool accept relations ?
Also my models come from 'Common' folder .. No clue why when I suppressed the relationships, the tool still generates those errors.

Any idea?

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges thanks for reaching out.

Hey so, yes the SDK Builder does accept relations, actually there is a complex decision three to decide how to handle these relationships, since some models may be public others private.

Anyway, I can think in 2 things.

1.- you are declaring both, the property for the relationship and the relationship, this will duplicate the properties and seems that is the error displayed. So, you don't need to explicitly define the property "categoryId" because you will duplicate, just leave loopback create these for you.

2.- About the access token I believe you are making the AccessToken public within your base-model.json configurations, just leave it private.. Anyway that was also fixed but in a further 2.1 beta version. If you don't like the idea of being in beta, just make the AccessToken private and the SDK will handle everything under the hood.

Also, I will be publishing the first release candidate for version for the version 2.1 within the next following days, there is a ton of improvements.

Cheers
Jon

**Comment by PhilippeCorreges** [comment]
@jonathan-casarrubias 

Thanks

**Comment by jonathan-casarrubias** [comment]
Hi @PhilippeCorreges does this issue persist? or can I close this issue?

**Comment by PhilippeCorreges** [comment]
I close it as I did not take the time to test it at the moment even if i understood your point.

**Comment by PhilippeCorreges** [comment]
Hello,
Just wanted to give an update on this.
I set AccessToken to public=false;
I added some custom relations (properly).
I regenerated the SDK dated today.
I updated the source to SDKBrowserModule instead of SDKModule

and everything is ok.

Thanks

**Comment by jonathan-casarrubias** [comment]
Wonderful!!!

I'm glad everything went well @PhilippeCorreges, I appreciate the time you took to verify and provide the feedback.

Cheers!!
Jon
