### ISSUE TITLE
Consider descriptive commit messages and change logs

### ISSUE THREAD

**Issue by JonnyBGod** [mean-expert-official/loopback-sdk-builder#235]
I find it very time consuming and even difficult to follow updates on this and your other projects.

Please consider adopting more descriptive commit messages, it would greatly improve keeping track of changes and overall understanding of the projects and features.

I would advise to adopt [AngularJS Git Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)

**Comment by JonnyBGod** [comment]
[commitizen](https://github.com/commitizen/cz-cli) helps a lot with this.

**Comment by jonathan-casarrubias** [comment]
Hi @JonnyBGod thanks for reaching out, I eill keep the current commit  convention because that automates the process of closing issues. 

If you want a better / more for human descriptions of any update just follow the milestone number you want to discover


https://github.com/mean-expert-official/loopback-sdk-builder/milestone/21?closed=1
