### ISSUE TITLE
API functions not using Models anymore

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#238]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ X ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [ X ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I just updated the sdk to RC2 and now I am getting a bunch of errors. Seems like the APIs/Services are different now. For example findById used to return Observable< Model > and now it returns Observable<{}>. Is this intentional and should I change the Logic of my App?

![image](https://cloud.githubusercontent.com/assets/5745805/20863683/6b7e4894-ba05-11e6-92d5-ee9e873cd880.png)

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag, I'm glad to see you back in here.

Hey so, yes that is a breaking change I need to fix a couple of issues and then I will write a blog about it and update documentation. [Read here for more context](https://github.com/mean-expert-official/loopback-sdk-builder/issues/200#issuecomment-261557173)

Now PersistedModel Methods are extended from BaseAPI and are not generated anymore within the Models.

This reduces a huge amount of lines of code and I decided to do the change before is too late.

What is happening is that these methods now are generic, you now need to pass the model type as in FireLoop.  I'm sorry for these issues but it is for good, it reduced almost 5k lines of code from the testing application sdk.

I hope this helps you migrate to 2.1 RC 

S

**Comment by dmastag** [comment]
Hi Jonathan,
Yeahh, I read that before but didn't really thought about the implications (I am watching this repo and checking the issues). Ok, so that is the new way to do connections understood.

**Comment by jonathan-casarrubias** [comment]
Yes I was worried about the implications, I know all the applications would be broken... It was a hard decision to make, but at the end it drastically improves the generated code.

**Comment by dmastag** [comment]
Does less code improve the performance also?

**Comment by jonathan-casarrubias** [comment]
Yes, but mainly because there is much less memory allocated... It also does improve the methods implementation so should be slightly faster.

At the end is the same number of calls to get a result (2 methods, 1 api call). In that terms I don't see an improvement, I don't think it can be faster as it is now when we talk about this specific case.

Client performance can be only improved by using FireLoop, but of course this will delegate the load to the server, so cache mechanism for each model is super important in order to maintain good performance in both, back and front ends.

Cheers
Jon

**Comment by dmastag** [comment]
Awesome, thanks for the explanation
