### ISSUE TITLE
Realtime on attachTo models

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#245]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hi Jon,
So I got this very-very unusual use case.
Currently I am tasked with moving our Enterprise App to NodeJS using Loopback. The problem is the old system is using ColdFusion with one codebase accessing hundreds of databases. So basically the app does something like this

```
<cfquery datasource="#session.accountcode#">
 <!--- The query --->
</cfquery>
```

This works neatly in ColdFusion but I am having a helluva time applying this in Loopback. What I basically do is this:

- have all the models set with no datasource (all dbs have the same data structure)
- a boot script to create all the datasources
- every time a request is made to the API, I check the access for the account code and use the attachTo function on the model to connect to the correct database

This is working with no problems but for some reason Realtime is not working here. I assume its because of attachTo function the Realtime connection / model has already switched to a different database?

So I would appreciate some pointers on what I should do or if I am doing it totally wrong and there is a less painful way to solve this.

Thanks
Julian

**Comment by jonathan-casarrubias** [comment]
hi @dmastag thanks for reaching out.

Hey so, neither the case if you use FireLoop or PubSub there is a mechanism to allow you that, I'm not sure the issue can be fixed for the PubSub, only by setting some sort of configuration but won't be that dynamic.

With FireLoop I think it can be done easier, since I have almost complete control of what I can do, and every ModelReference should now be registered within the server, at that moment you could pass a configuration to attachTo that reference to a specific DB.

In the first option you would need to manage a configuration in the server to handle this, not so dynamic. In the second option you would need to decide from the front-end which model reference goes to X or Y db reference.

Which can be pretty cool because, you could have 1 company modelReference pointing to 1 db, and 1 company modelReference pointing to another db.

Of course it is not possible right away and I would need to add it to the list of features

Is that last one of the options -with fireloop- something like you are looking for?

**Comment by dmastag** [comment]
No problem. I could go with either way.
In the meantime, could you give me a few pointers on what I should do as a workaround?

**Comment by jonathan-casarrubias** [comment]
Ok I have been analyzing and the PubSub will be definitely impossible, because it hooks from the result of a remoteMethod operation, which means that by that moment the data should be already persisted, so that is discarded.

FireLoop does register the FireLoop Reference prior the operations so it still is possible, but there is no easy work around, you would need to modify both, the SDK Builder and the Component Realtime, the former should modify the FireLoopRef in order to add a property for the datasource to be selected within the ctor.

Then you need to receive that in the FireLoop module within the real-time component to attach the model to the datasource sent by the client.

Thinking again I don't think you could have different datasources for the same model but at least you could register the datasource from the client.

I'm sorry not to bring a quick work around for this.

**Comment by jonathan-casarrubias** [comment]
Need to clean the repo to open space for LB4 related issues.
