### ISSUE TITLE
LoopBackConfig "First Steps" documentation

### ISSUE THREAD

**Issue by opyate** [mean-expert-official/loopback-sdk-builder#247]
*DISCLAIMER*: newbie alert.

This is a question about  2.0.10 (Stable). The [First Steps](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/4.-First-Steps) documentation states:

> I know some of you may be asking your self; Why do I need to configure this in every single component? And the answer is because we want to decouple our components as possible, so each of these will have their own configuration, therefore you will be able to point your components to different API instances and versions.

But if you look at the way the class is imported:

    import { LoopBackConfig } from './shared/sdk/index';

This imports the *class*, not an *instance* of the class, right? If any component now calls `setBaseURL` which changes the static property `path`, it would reflect everywhere `LoopBackConfig.getPath` is called.

In fact, I did a little experiment in LoopBackConfig where I added `constructor() { throw new Error('Cannot new this class'); }` and got no errors during the use of my app.

Please correct me if I'm wrong! If not, then this is dangerous advice for the current stable version that generates a `LoopBackConfig` (I'm thinking "race condition").

(the documentation could potentially also describe the other case where one's SPA is the only client of the API, and one might choose to use just one instance and version of an API, so a good place to call `setBaseURL` is in `app.component.ts`'s ctor or `ngInit`)

**Comment by jonathan-casarrubias** [comment]
Hi @opyate thanks for reaching me out and also for bringing this up...

I believe this is a good topic to be discussed, the SDK Builder has been around for a while, and many things have changed since I wrote that statement. It's just difficult to keep documentation up to date when so many features are being launched.

Actually the sdk now generates the configuration from the Server, so whatever you set in your server config it will be generated in here.

Second, at that moment no matter this was a static class, for some reason when you changed from sections In Angular 2 you didn't have the url config from the last section, but the default or empty. Not sure if that was fixed when it was migrated to webpack.

Honestly the last 4 or 5 months I have been deeply working in the real-time features and angular universal integration so I have not modified anything related to the config since has never caused an issue to anyone.

But if you find a bug or error related to the way you configure the sdk, I will appreciate you rise an issue describing it.

I hope this helps you clarify your question.

Cheers
Jon!
