### ISSUE TITLE
Add LocalStorage API

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-sdk-builder#265]
#### What type of issue are you creating?
- [X] Enhancement

#### What version of this module are you using?
- [X] 2.1.0-rc.n (2.1 Release Candidate n)

Write other if any:

#### Please add a description for your issue:

Persisting data in browsers is getting a downside after cookies storage was implemented, it needs to remain within the SDKBrowserModule in order to allow angular universal to work, but it does requires to provide a way to persist custom data in local storage.

**Comment by Sturgelose** [comment]
@jonathan-casarrubias Hi, one question, you added this LocalStorage API, in this milestone, and also there are some other storage options with cookies and similar.

However, is this documented anywhere? I can't see anything related in the wiki and I'd like to know how to use this storage options to store some of the models' data locally (we are trying to use Loopback's sync feature)

**Comment by jonathan-casarrubias** [comment]
Hi @Sturgelose thanks for reaching me out.

Hey so yes what I did is to provide a storage mechanism depending on the environment you are running... To use the storage api, after you install the SDKModule.forRoot(), you will need to inject in your constructor the StorageAPI which basically provides you with 3 methods, set, get and remove.

Behind the scenes StorageAPI may point to cookies, or local storage, again depending on the environment. But later I received a pull request that allows you to decide and select which storage provider you want to use.

For that you need to do it when the SDKModule.forRoot() is being installed, as followa:


````js
// Do necessary imports here, use sdk/index.ts as reference

imports: [
  SDKModule.forRoot({
    provide: InternalStorage,
    useClass: CookieBrowser
  });
]
````

That way you may change from CookieBrowser to other available providers within the `sdk/storage` directory

I hope this information helps you clarify your questions

Cheers
Jon

**Comment by Sturgelose** [comment]
@jonathan-casarrubias 

Thanks for the fast answer. Sounds good! I saw a snippet of the code in another issue on how to use this, then:
```
import { SDKStorage } from './shared/sdk/storage/storage.swaps';

@Component(...)
export class MyComponent {
  constructor(
    private storage: SDKStorage
  ) {
    this.storage.set('something', this.something);
    console.log(this.storage.get('something'));
  }
}
```

So, mostly with this we can persist custom data, as I now understand.

From our side we are trying to persist models for offline usage of the app, so, when we do a GET from the SDK we can fetch from the API and persist it in a database, or we can otherwise load from the database instead of the API when we do not have internet. I think something like this is possible with the Loopback Sync feature, or not sure if FireLoop provides a solution like this, but do you know if we could achieve something like this with the help of the Storage API?

If you think this is diverging too much from this issue (which is closed), I can open it in another issue  to have a better discussion...

Thanks a lot again!

**Comment by PhilippeCorreges** [comment]
Hello,
I set:
`SDKBrowserModule.forRoot({
      provide: InternalStorage,
      useClass: BaseStorage
    }),`
in my app.module.ts for my pwa to be able to use localstorage.
Is that all ?

I am getting an error : Cannot find InternalStorage.

Any help would be greatly appreciated.

Philippe
