### ISSUE TITLE
How to add a hook executed before each server request ?

### ISSUE THREAD

**Issue by marcbuils** [mean-expert-official/loopback-sdk-builder#276]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ x ] Question

#### What version of this module are you using?
- [ x ] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hi,

I use loopback for my back end, but the authentication is managed by Firebase.
So, I should refresh the token with the firebase sdk before each server request.
It's possible to register a callback who will call before each server request ?

Thanks,
Marc

**Comment by jonathan-casarrubias** [comment]
Hi @marcbuils thanks for reaching out!!!.

Hey so, I'm sorry but this is the first time anyone asked for this functionality, but this is why the project keeps amazingly growing, because of this types of questions/request.

So, again..There is nothing implemented right now to allow you hook before a request.

I'll try to think in a good approach for this

Cheers
jon

**Comment by jonathan-casarrubias** [comment]
Need to clean the repo to open space for LB4 related issues.
