### ISSUE TITLE
Unable to use with api behind http basic auth

### ISSUE THREAD

**Issue by mrfelton** [mean-expert-official/loopback-sdk-builder#294]
#### What type of issue are you creating?
- [X] Enhancement
- [X] Question

#### What version of this module are you using?
- [ x ] 2.0.10 (Stable)

It seems that it is not possible to access an API that is protected with HTTP Basic Authentication. I have tried configuring the api url using the standard form as:

```
https://user:pass@domain/
```

However, the username and password gets lost along the way. From looking at the code, it seems that you are currently setting the Authorization header if an access token exists, and if so you are setting the Authorization header as the token - which won't work for apis that are behind http basic auth. I think you should use the `access_token` url parameter to pass the api token instead of the setting the token in the `Authorization` header, and you should extract the username/password from the URL and set that as the `Authorization` header.

**Comment by jonathan-casarrubias** [comment]
Hi @mrfelton thanks for reaching out.

Hey so, first of all I don't consider this a bug since this modules is implementing a valid authentication mechanism supported by loopback

https://loopback.io/doc/en/lb3/Introduction-to-User-model-authentication.html
https://loopback.io/doc/en/lb3/Making-authenticated-requests.html

**Comment by mrfelton** [comment]
@jonathan-casarrubias fair enough. I'll do some more investigation and try to work on a patch and submit a PR that resolves this issue.

You are right that using the `Authorization` header is _a_  valid approach that is supported by loopback - however, it seems to be an approach that suffers from the issue of a conflict with standard http basic authentication.

Using the `access_token` query parameter is another valid approach that is supported by loopback - and this approach does not suffer from the same problem, so potentially this may be a better approach to take.

My diagnosis of the problem could also be at fault here. Basically, the problem I'm seeing is that with a configured api url of `https://user:pass@domain/` the api just returns 401 rejection by http basic auth - which does not seem to happen in the official loopback sdk.

Is there any specific reason why you opted to use the `Authorization` over the `access_token` query parameter?

**Comment by mrfelton** [comment]
BTW, here is a pretty decent article that gives the lowdown on the header conflict issue and the problems with using the `Authorization` header.

http://blog.digitopia.com/tokens-sessions-users/

**Comment by jonathan-casarrubias** [comment]
Hi @mrfelton, actually it is kind of funny because originally it was being sent through query string, but other users requested to be moved to the header because it was best for their use case.

I mean that was just part of the problem they also wanted to see a more readable queries than the generated query strings that include LoopBack Filters, it is almost imposible to debug using query string when filtering requests.

So maybe a balanced point where the filters are sent through headers but maybe only the access_token could be passed through query string, that way won't be difficult to debug and would help you with the basic http auth you are trying to achieve.

**Comment by mrfelton** [comment]
Hey @jonathan-casarrubias - Yes, that could work. Or possibly make that configuration optional so that users can choose the scheme that works best for them.

I think the official loopback SDK allows users to specify the specific access header that is used, making it possible for users to configure it to use the `X-Access-Token` instead. This would be a nice option to have (although this requires that the loopback session middleware be configured in a particular way to support it).

And then additionally, an option to use the `access_token` query string instead - which doesn't require any changes on the loopback backend

**Comment by jonathan-casarrubias** [comment]
Closing due inactivity, need to clean the repo to open space for LB4 related issues.
