### ISSUE TITLE
socket errors not been handled and not fed into Observables

### ISSUE THREAD

**Issue by mike-packetwerk** [mean-expert-official/loopback-sdk-builder#296]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.7 (2.1 Release Candidate 7)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
In flref.ejs you create three new subjects. A single example being:

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/angular2/shared/models/flref.ejs#L158

Unfortunately you do not handle any socket errors, so it is possible that these new observables will never emit/complete and certainly not error. I'm not meaning in channel errors (ie error information passed back from the server), but rather local socket client library errors.

In my case  a timing issues exists such that the initial socket traffic passes over the long polling method before the socket is upgraded to a websocket. In this case a couple of pull/broadcast messages get emitted but before hitting the wire the socket is upgraded. The socket library sends these packets as polling and the server rejects them as it has already upgraded to websocket method and discarded the original id used by polling.

Adding
```
    this.socket.on('disconnect', error => sbj.error(error));
```
into each of the affected functions fixes the problem in the sense that my client code can retry the connection/handle the lack of response. However, I'm not clear of the implications with leaking memory/adding an every increasing number of listeners as the socket is really global to the file.

BTW, I tried listening to `this.socket.on('error')` but it never fired.

**Comment by jonathan-casarrubias** [comment]
Hi @mike-packetwerk thanks for reaching out, also for elaborating the issue.

I just want to confirm, isn't this issue the same as this one? https://github.com/mean-expert-official/loopback-sdk-builder/issues/281

That is already fixed but not published, will be published by next version.

**Comment by jonathan-casarrubias** [comment]
Ok, but you have I think at least 3 problems remaining:

*) in the disconnect handler, you broadcast the disconnect message before actually processing the disconnect. If I wanted to `retry` the onReady it creates an infinite loop. ie I think the code should be:

```
  this.disconnect();
  connectionSubject.error('disconnected');
```

**Ok that make sense, I will try to move it before firing the vent.**

*) I think you have a kind of race condition with your `if (this.connected)` statement. Between calling `onReady` and the connection being established (the `connect` event) is enough time for many additional `onReady` calls, all which will create new `new FireLoop(this.socket, this.models);` The result is the cache of FileLoopRefs is not globally unique.

**I think this can be solved by adding a new status "connecting" and wait until it is actually connected o there are no multiple FireLoop and connections**

*) The original problem I reported above still remains. ie calls into FileLoopRef might never return (emit/errror/complete). It seems unnecessarily messy to ask uses of FileLoopRef to have complex Observable pipelines needing to track `RealTime.onDisconnect` with say `FileLoopRef.on` simultaneously. Actually, I'm not sure it is possible to get it right. I would be happy to see you directly address this point, and find my logic hole.

I'm not totally agree with you on this one, because decoupling functionality to later be used with other modules it does not seems messy for me.

The problem with this project is that it manage several use cases and people asking requests only take care for their specific use case, as I said there are 3 different ways to communicate through websockets using the SDK Builder and all of them share this issue. You are focusing in your personal specific issue, but you are not taking in mind that doing the way you are asking, would not need not to duplicate but triplicate code.

So yes, making FireLoop references to handle all of these issues would fix your problem, but would lead to many problems to other persons.

Anyway, it is in my plans to separate the SDKs once the moment arrive

**Comment by mike-park** [comment]
(Mike from another account) 

I understand you have competing requests and 3 subsystems, however this is not a request. I believe this to be a serious bug. 

I'd appreciate if you would share example code of how you'd expect an end-user can work successfully with the suggested setup in the face of FireLoopRef.on never returning any event.

**Comment by jonathan-casarrubias** [comment]
Yes I agree we have a bug in here, I'm working on to resolve it... we are just in disagree where the bug should be fixed, but that my friend is where the big ideas born, from good brainstorming like this.

Let me finish the approach I'm working on and I will add an example in here.

If you still feel it is not the right approach, then lets discuss and try to get the best from this.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Ok at the end I was able to handle disconnectios inside the sdk, the fix is transparent for developers.

While you create your fireloop references inside onReady. The SDK will internally handle everything for you.


The onDisconnect, onAuthenticated and onUnAutorized events are not for uou to handle the reconnect but to notify the user through UI that any of these events happen.

Socket io will automatically reconnect when possible and the SDK will recover the client subscriptions state in both server and client.

It will clean all the listeners and onReconnection will automatically setup everything again.

The test application inside this repo is an example. If you see there are no implementation changes, other than subscribing within the app component to each of the connection statuses
