### ISSUE TITLE
Get exact constructed url

### ISSUE THREAD

**Issue by BostjanPisler** [mean-expert-official/loopback-sdk-builder#323]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Is there a way to read the exact url that was called through the modelApi call? 
I'm asking because I use a dedicated service for each model endpoint in angular 2 and I added a simple caching mechanism which I would like to expand to be even more precise and I need the url to use as a "unique key" for the cached data. 
Or if there is a way to inject this functionality into the request/response object maybe? 

Thanks for your feedback.

**Comment by jonathan-casarrubias** [comment]
Hey @BostjanPisler right now there is no mechanism implemented for that, though using RxJS should be really easy to implement, maybe a http call stack service that fires on every call so you can persist these calls, but what won't be easy at all will be to return the url from the same method you use to do the actual call, this is mainly because returns an observable to be subscribed.

Maybe I will add a CallStack service that can fire that for you but my concern is how to easily coordinate both, well not sure if will be as easy as receiving it in a returned value.

**Comment by BostjanPisler** [comment]
Yea my thoughts were similar. What I'm doing now is stringifying the filter object and store that for each model endpoint and it serves as a basic solution.
