### ISSUE TITLE
Please provide AccessToken in socket connections

### ISSUE THREAD

**Issue by tobibrandenberg** [mean-expert-official/loopback-sdk-builder#332]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

It would be fine to be able to get the AccessToken from realtime functions in hooks to get the current user

**Comment by jonathan-casarrubias** [comment]
Hello @tobibrandenberg thanks for reaching us out.

Hey so, right now you can actually get all of that by using the AuthService, that way you can get the access token, current user, etc. Though is not realtime, this is because by the moment the authentication is being done, there is no socket connection just yet, the socket connection will be created once the client is already provided with a token, that is why the AuthService and any UserService using HTTP calls are used for this purpose.

I hope this information guides you on what you are trying to achieve.

Cheers
Jon

**Comment by tobibrandenberg** [comment]
Hi @jonathan-casarrubias !

Thanks for the reply! I tried to achieve to get the user who made the socket request on server side because I wanted to set some db fields in my server code... I don't have any idea how to get the user by using the AuthService in backend. Could you please provide an example?

By the way: Thank you very much for your really, really great work! I makes life much more easier for us!

**Comment by jonathan-casarrubias** [comment]
ok I see your point now.

Mhh I need to verify, I do have a reference for each of the authenticated users within the socket instance for each connection, though for security purposes that is not accessible from other parts of the framework.

I know with plain loopback you can get the access token from the user doing the request but I'm not sure the method verifyAccess the provide set the token within the context, since I do use the users tokens to validate that each of the calls are authenticated, they provide a method to validate if the token has access, but what I'm not sure if they pass it.

If then don't do that, then I will need to provide a way to set in a context some information about the user doing the request.

BTW; Thanks for your nice words!! I hope you to build amazing things with these tools.

cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Closing due inactivity, also need to clean the repo to open space for LB4 related issues.
