### ISSUE TITLE
POST JSON Object

### ISSUE THREAD

**Issue by denzelwamburu** [mean-expert-official/loopback-sdk-builder#348]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

How do i post a json to the endpoint using the `.create()` method?
My Json object is
` class Text {`
    ` constructor(`
     `  public _id : number,`
`       public address : string,`
 `      public date: string,`
  `     public body: string,`
   `    public thread_id: number
   `  ) {}`
  `} `

  `let texted = new SmsData(1190, 'Nineth', '1483017005992', 'Long story short', 780);`

This doesn't seems to work,
 `private text : TextModel = new TextModel({all: texted});`

**Comment by jonathan-casarrubias** [comment]
Ha that is strange the last one should work

````js
private text : TextModel = new TextModel({all: texted})
````

I will need to verify why it got broken. thanks for reporting

**Comment by denzelwamburu** [comment]
Hi @jonathan-casarrubias , i managed a work around, thought i don't know how theoretically correct this is,but it works 😺

`private text : TextModel = new TextModel((this.texted))`

`  create(): void {
    this.reference.create(this.texted).subscribe((instance: Sms) => console.log(instance));
  }`

**Comment by jonathan-casarrubias** [comment]
@denzelwamburu I see, also I reviewed the code..

So... in order to create a model passing the data in the constructor, you need to pass a valid TextModel.

I was assuming  that { all: text } was a valid TextModel interface, but it seems that was not correct.

So, again you can pass an object that includes properties defined also in TextModel.

Also, I'm now assuming that you are not using VCode or an IDE that show you the typing errors, if you are not I recommend you to start doing it, you will avoid these issues.

I'm glad you were able to make it work  I will close this issue now.

Cheers
Jon

**Comment by denzelwamburu** [comment]
@jonathan-casarrubias Am using VsCode, apparently it didn't catch that error.

**Comment by jonathan-casarrubias** [comment]
@denzelwamburu I see... if I remember well you have a FireLoop Project, somehow VCode requires the tsconfig to be on the root of the project to fully work, although it does find some issues -sometimes. 

I usually need to open vcode in the client app project or the fireloop folder, both contain their own tsconfig.

That may help you find more typescript related issues.

As a note, I can not leave the tsconfig on the root of the project since either the server or clients will be compiled separately.

Regards

**Comment by denzelwamburu** [comment]
Hi,
That's man.
One more thing. Could you look up a the fireloop site. It seems to be down.
The docs are pretty helpful..
thanks.

**Comment by jonathan-casarrubias** [comment]
@denzelwamburu I fixed that issue a couple of hours ago, but since I needed to update the DNS it make take some time to replicate on your area... It should be fixed really soon.

Cheers!
Jon
