### ISSUE TITLE
AccessToken Interface userId as string istead of number

### ISSUE THREAD

**Issue by rodplata** [mean-expert-official/loopback-sdk-builder#355]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

With the new version changes, the AccessToken Interface set the `userId` as number but, for the users (like me) that use cloudant for example, the id are alphanumeric, so that needs to be a string (just like before) not a number

**Comment by jonathan-casarrubias** [comment]
yes you are right, since AccessToken is usually not public I need to add a "back up copy" of the AccessToken that got old, when I updated to the new is basically what I got. Though originally I changed it for any, so this problem would not appear, but it seems that now I will need to update it to any again.

The access token topic is being a pain because of the folks enabling the AccessToken vs the ones that Does not. any way, I'm adding this as a bug and try to fix it asap.
