### ISSUE TITLE
socket errors on strongloop process manager with multiple cores

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#368]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-rc.n (2.1 Release Candidate 8.3)
- [ ] Other

Write other if any:
Am using with Ionic 2 Angular 2
#### Please add a description for your issue:

Hi All,
As always, great work.
So I am moving my server to production using Strongloop Process Manager and have been given a server with 8 cores, all of them I intend on using plenty. The problem is that once using multiple cores I am getting the following in the console:

WebSocket connection to 'ws://192.168.0.40:3004/socket.io/?EIO=3&transport=websocket&sid=VA0ClJ2a41iiYTTaAAEI' failed: Error during WebSocket handshake: Unexpected response code: 400

This goes away if I go back to using 1 process.

I have been trying for days to get around this, switching version of the sdk from beta 8 to rc 8.3 without any luck.

Would appreciate if I could be given any pointers as I have no idea what to do right now.

**Comment by dmastag** [comment]
Hah, I just found this old issue from you @jonathan-casarrubias 
https://github.com/strongloop/strong-pm.io/issues/7

So does this mean that I cannot use Strongloop Process Manager with sockets? I really like strong-pm for the build and deploy feature, but if I have to drop it then I will.

**Comment by jonathan-casarrubias** [comment]
Hi @dmastag yes I was able to pass  that issue by doing several things, actually I remember we had this conversation before, when you asked why using mongodb instead of sql.

Anyway, first you need to make your load balancer sticky so every requests goes to the same machine every time, but there are other parts still missing, but not related to let you connect.

The part missing is the socket.io-adapter but that can be done from your side not necessarily from inside the component, check about socket.io adapter and you can chose between mongo or redis.

I added you already to the slack channel there are other guys that already staged in balanced environment you may get more advice on your connection issue

**Comment by phra** [comment]
@jonathan-casarrubias
regarding this, i saw the [solution](https://docs.feathersjs.com/scaling/readme.html#cluster-configuration) of [feathersjs](https://github.com/feathersjs/feathers) to this, that is forbid the http fallback and permit only native websocket connections that are stateful.

what do you think about it?

**Comment by dmastag** [comment]
@phra would this mean I have to install featherjs into my server/server.js file ?

**Comment by phra** [comment]
no, it means that also loopback or fireloop should follow their solution in order to not require a sticky load balancer.

**Comment by jonathan-casarrubias** [comment]
@phra @dmastag there are 2 things that needs to be fixed on clustered environments.

1.- Either use StickySessions or force WebSockets (As per @phra suggestion).- when using long polling connection, socket.io will make several request to achieve the handshake, responding  from different instances won't allow to success on the handshake.

Sticky session is not a good idea because either we use PM2 or ProcessManager, we have not access to the moment these managers create the cluster, so the only thing we can do to fix this is to force WebSockets.

2.- There is a second problem, in order for all the instances to be on the same page, in other words: Different clients connected to different instances, they all should always receive the subscribed data, regardless of which is the instance that received the original request.

To fix this, a socket.io-adapter should  be implemented, and that might be different depending on the datasource name and type, but this can be done only using redis or mongodb.

So I think this can be fixed by adding options that define which datasource will be used for having all the clients and server instances on the same page.

I will publish a small patch in both, the client and the server to force the WebSockets in order to fix the handshake issue and also maybe accepting some parameters to setup the adapter, this last one is more likely for convenience since this can be also done from your side.

Anyway, I'll work on it and publish a small patch for that, will notify so you can test it.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Ok I implemented this, of course it fixed the handshake problem and the second problem I described, but something unexpected happen, sometimes after it successfully connect it just disconnect right away, that never happen to me before... so I'll need to verify why

**Comment by phra** [comment]
@jonathan-casarrubias in the past to notify all the cluster instances i used [socket.io-redis](https://github.com/socketio/socket.io-redis) (plus [socket.io-emitter](https://github.com/socketio/socket.io-emitter) if the socket.io endpoint is separated from the apis endpoint.)

**Comment by jonathan-casarrubias** [comment]
@phra Since I know there are several adapters available, what I'm doing is to allow you guys install the one you prefer, and providing an interface through the component options to setup the adapter..

The adapter will be automatically loaded according the adapter you install and the settings you pass.

So you would be able to keep using socket.io-redis as adapter, while others might decide to use the mongodb one..

Regards

**Comment by jonathan-casarrubias** [comment]
https://github.com/mean-expert-official/fireloop.io/wiki/Scaling-Fireloop
