### ISSUE TITLE
Generated remote methods get a wrong observerable type

### ISSUE THREAD

**Issue by Undrium** [mean-expert-official/loopback-sdk-builder#369]
```
  function buildObservableType(model, method) {
    let type = 'any';
    if (
      method.name.match(/(^createMany$|^find)/g) ||
      (
        typeof method.returns === 'object' &&
        (method.returns.type === 'array' || Array.isArray(method.returns.type))
      )
    ) type = `${model.name}[]`;
    if (method.name.match(/(^create$|upsert|^findBy|^findOne$)/g)) type = model.name;
    return type;
}
```

This function caused some trouble to me as I had some custom remote functions named "find", the idea of having a more specific type than any is nice. However here my ObservableType got the model return without a capital letter which caused my application to crash when building. So my function findHouses got the return type Observable<house> instead of Observable<House>. This is probably a really quick fix. 

Another note, is there really good practice that all methods containing the name "find" gets this treatment?

**Comment by pwarelis** [comment]
I have a feeling that `^findBy` was supposed to be `^findBy$`.

**Comment by jonathan-casarrubias** [comment]
@pwarelis not really, since there are no plain findBy methods, and usually the findBy Methods would return a single instance, but there is no where there is written that must be like that. But since LoopBack is not really typed, it is really complex to have an exact typing mapped according the settings.

So based on that  @Undrium  we have followed patterns, for instance "find" will usually return an Array and findBy will usually return a single instance, it has been improved but there still are other validations that can be done.

In the other side f you are getting a lowercased observable type I can assume you are creating your models in lowercase, which the convention would be to  do it in Capital case.

That last point has been a headache because not all the people does it and since loopback won't complaint, it creates issues when passing to a much more strict environment like typescript. Again this has been improved over the time by me and by other guys sending pull request, but is hard job to create a typed SDK from a non typed environment.

So maybe following these patterns will help you while we all figure out how to keep improving the generation of the typed sdk from a non typed framework.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
I will close this one since it is out of the scope, need to clean up the repo for the next version
