### ISSUE TITLE
non ascii value in filter

### ISSUE THREAD

**Issue by alert83** [mean-expert-official/loopback-sdk-builder#418]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

why filter should be added to header?
request header does not accept non ascii symbols.

**Comment by jonathan-casarrubias** [comment]
Hey guys, thanks for reporting..

Originally the filters where being sent over url, but some people had issues because of really complex queries with multiple includes.

But that affects you because in headers your characters are not valid, so I can not simply choose between one or the other any more.

What I'm doing is adding a method in the LoopBackConfig to allow you define which method you want to use headers or url.

So now you just need to configure the SDK to use URL instead of headers (which is default)

````js
import { LoopBackConfig } from './shared/sdk';
LoopBackConfig.filterOnUrl();
````

Cheers,
Jon
