### ISSUE TITLE
Plus signs are removed in requests sent from Angular

### ISSUE THREAD

**Issue by pbouda** [mean-expert-official/loopback-sdk-builder#573]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.0.10 (Stable)
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

When I sent a request to a LB remote method that uses query params the plus signs are removed from any data. This is a bug in Angular, see for example:

https://github.com/angular/angular/issues/11058

I tried to add the workaround they mention to the current master, and it seems to work fine. The PR is [here](https://github.com/mean-expert-official/loopback-sdk-builder/pull/572), but I saw that you want PRs only for development. But in the development branch you already switched to the new HttpRequest in `@angular/common/http`. I can send another PR also for development, but when do you plan to release the next version? I would need this fix soon, and would like to see it also in master. What do you think? Do you think this fix makes sense in the the first place, and where should we apply it?

**Comment by jonathan-casarrubias** [comment]
Hey @pbouda thanks for sending your patch, currently master is behind development because there is a very weird dependency issue that makes the CI to fail, therefore I'm unable to merge into master until that issue is fixed.

But I was bottlenecking the progress sent to Dev so I decided to publish what is in DEV, so whatever you install now from NPM (2.2.0) is what we have in dev, so the Ideal would be that you implement your patch over dev instead of master.

Cheers
Jon

**Comment by pbouda** [comment]
Ok, I sent a new PR: https://github.com/mean-expert-official/loopback-sdk-builder/pull/589

**Comment by jonathan-casarrubias** [comment]
landed
